### ISSUE TITLE
ChangeIndicatorToMoveStateToVariable Bug

### ISSUE THREAD

**Issue by NilsSve** [NilsSve/DfRefactor#1]
There is a bug in the ChangeIndicatorToMoveStateToVariable function of the main repository file cRefactorFunctionLibrary.pkg.

**Comment by 2WA** [comment]
Do you prefer to fix it first and after that return to the Tokenizer function?

**Comment by NilsSve** [comment]
The Tokenizer function has top priority.

**Comment by NilsSve** [comment]
Fixed!
