### ISSUE TITLE
TestBench - Multiple Refactoring sessions sometimes results in "scrambled" refactored code

### ISSUE THREAD

**Issue by NilsSve** [NilsSve/DfRefactor#13]
Sometimes after the "Start Refactoring" button has been pressed several times for the same unchanged LegacyCode.pkg, the refactored code is somewhat "scrambled".

This is particular for the TestBench program and seems to have nothing to do with the actual refactoring functions.

The problem can often be seen as e.g. a ")" character right after a "Begin" keyword. Parenthesis can also get to be wrong inside of expressions.

This does not have a high priority at the moment.

**Comment by Caeylinity** [comment]
This may be related, but mine just stopped refactoring altogether after a while of changing the code and pressing 'Refactor Code'. I had to restart the program to make it work again.

**Comment by NilsSve** [comment]
To ease the pain of this somewhat, a new toolbar button was introduced; "Refresh"
It will clear the Refactored editor content and reload the Legacy Code editor file.

**Comment by NilsSve** [comment]
There definitely is a problem with the Scintilla editor and conversion between OEM and UTF8 under DF 23.
It is this that causes these weird phenomena described above. 

Note: This only happens when "extended characters" (outside the a-z range"), are used in a string.

**Comment by NilsSve** [comment]
I think I finally nailed this bug.
It turned out that the cSciLexer.pkg was using a "(Length(" function call when it should have been "(SizeOfString(" when compiled under DF 20.0 and up.
