### ISSUE TITLE
The Tokanizer function needs to be improved

### ISSUE THREAD

**Issue by NilsSve** [NilsSve/DfRefactor#2]
The Tokanizer function needs to be improved *and* implenented/called from (almost) all other functions in the RefactorFunctionLibrary.pkg repository.

**Comment by 2WA** [comment]
Continued enhancing the tokenzizer function in the cBaseRefactorFunctionLibrary.pkg

**Comment by 2WA** [comment]
Wonderful!

🤜🤛

 

Anderson Rodrigues

+55 (11) 9 9521-3889

 ***@***.***> ***@***.***

Skype: altechso_anderson
