### ISSUE TITLE
Multiple issues with the 'Functions List' tab

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#20]
- By default, "ChangeCalcToMoveStatement" is selected, but when I deselect it, 'Selected' still says "1".
- After deselecting "ChangeCalcToMoveStatement" (default selected) and returning to "Test Bench", then clicking "Use selected Functions only", it will say "33" the first time. Deselecting and reselecting will say "1" (which is still incorrect, but that circles back to issue 1)
- After deselecting "ChangeCalcToMoveStatement" and trying to exit the application through the windows X button I get a prompt asking "Changes exist in Functions List. Exit this Application?". When I click "Yes", the application closes normally, but when I click "No", nothing happens, but the entire application is locked out and no butters can be clicked anymore. I have checked and there are no sneaky hidden error windows.

**Comment by Caeylinity** [comment]
Update:
- Selecting a second function (other than the default selected one) will keep 'Selected' at "1". It seems that sometimes the selection values are inverted. Just clicking around and playing with selections gives weird results (number either too high or too low).

**Comment by Caeylinity** [comment]
Half of this problem seems to be caused by records not saving upon changing the box status (checked/unchecked) but only on row switching, but nothing is saved when switching tabs. Maybe an automatic save should happen when swapping away from the Functions List tab?

**Comment by NilsSve** [comment]
A mix of bugs caused the issue. There were a couple of bugs in the Functions datadictionary class. The refresh logic for the view itself was also flawed.
Fixed!

**Comment by NilsSve** [comment]
I found one more bug causing the counting of selected functions to get out of wack. Fixed!
