### ISSUE TITLE
RemoveUnusedLocals does not remove unused local

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#22]
I have the following function:

```
Function BitShiftLeft Integer iPositions BigInt iOptShiftVal Returns BigInt
    BigInt iInt localIntRemovalTest
    Boolean bLocalRemoveTest
    String sLocalRemoveTest
    Integer iLocalRemoveTest
    UInteger uiLocalRemoveTest
    tTest tTestLocalRemoveTest
    
    If (iPositions > C_$MaxPositionShifts) Begin
        Error DFERR_PROGRAM C_$PositionValueOutOfBounds
        Function_Return 0
    End
    Else If (iPositions <= 0) Begin
        Error DFERR_PROGRAM C_$PositionValueNegativeOrZero
        Function_Return 0
    End
    
    Move (2^iPositions) to iInt
    
    If (num_arguments > 1) Begin
        If (iOptShiftVal > C_$MaxInt64) Begin
            Error DFERR_PROGRAM C_$ValueOutOfBounds
            Function_Return 0
        End
        
        If (iInt * iOptShiftVal > C_$MaxInt64) Begin
            Error DFERR_PROGRAM C_$OutcomeOutOfBounds
            Function_Return 0
        End
        
        Function_Return (iInt * iOptShiftVal)
    End
    
    Function_Return iInt
End_Function
```

Note: tTest is a struct i defined above the function

None of these local variables get removed after refactoring so it doesn't seem to simply be a single type that wasn't accounted for.

Could this be because of the 'Type' setting? It's set to "Other - One File" by default, but I can't seem to change the setting; it just doesn't save.

**Comment by Caeylinity** [comment]
Update:
- I seem to be able to change the Type to other types using the prompt button in the Functions List view

**Comment by NilsSve** [comment]
Good find. The RemoveUnusedLocals refactoring function hasn't been tested when used in the TestBench, so this needs to be investigated.

"Could this be because of the 'Type' setting? It's set to "Other - One File" by default, but I can't seem to change the setting; it just doesn't save."

Trying to change the "type" setting is never advisable. The "type" setting is governed by the function interface (aka calling convention) for a particular refactoring function. In this case the "RemoveUnusedLocals" is *not* a line-by-line function., instead it expects a full source file as a string array.

**Comment by Caeylinity** [comment]
> Trying to change the "type" setting is never advisable. The "type" setting is governed by the function interface (aka calling convention) for a particular refactoring function. In this case the "RemoveUnusedLocals" is not a line-by-line function., instead it expects a full source file as a string array.

Good to know, but weI both know the end-user will try to change this setting and after many attempts I was able to get it to save resulting in the issue reported here: #24. I have no idea how it ended up saving, because it seems to revert to the previous value most of the time, even after clicking 'Save'.

**Comment by Caeylinity** [comment]
Maybe it should be made read-only in "Function Maintenance" as well?

**Comment by NilsSve** [comment]
The bug that caused the RemoveUnusedLocals function to fail totally was a bug in the system function (cBaseFuncLib) named _MethodName. The refactoring function itself also had some issues. They should all now be fixed.

**Comment by NilsSve** [comment]
The help for this function has been made clearer. The help now states that it doesn't handle struct variables.
Remove variables from functions and procedures that aren't used. A limitation is that it does *not* remove unused struct variables.

**Comment by NilsSve** [comment]
> Maybe it should be made read-only in "Function Maintenance" as well?

No, I don't think that is needed. The reason is that only very experienced developers will ever use the TestBench program where this can be changed. We expect that those developers know how to handle it.

**Comment by Caeylinity** [comment]
It still doesn't seem to work for the default included `BitShiftLeft` function. The struct `tTest tTestLocalRemoveTest` is still there after refactoring.
