### ISSUE TITLE
Illegal datatype conversion error

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#24]
Setting RemoveUnusedLocals to Standard - Line-by-line, assuming it works, because 90% of the time this setting doesn't save at all, results in an 'Illegal datatype conversion' error, seemingly because the array of input files is empty. Not sure how this all works under the hood, but I did a quick call-stack check.

**Comment by NilsSve** [comment]
The interface for the RemoveUnusedLocals is *not* a type "Standard Line-by-line" refactoring function. So this should *not* be changed. So this would be a user error that simply can't be guarded against and something we have to live with. Note you that it is expected that only experienced developers will ever use the TestBench program and it is only here that this value can be changed.

However, in the "Functions List" view, it was possible to edit this value and that was a bug.
Fixed!

Now to the more serious bug here and that is that the RemoveUnusedLocals doesn't work as it should and this needs attention.

**Comment by Caeylinity** [comment]
Yeah, we discussed this yesterday, but by that point I had already made this issue (and referenced it in our other conversation). Not being able to change the setting at all should prevent all further instances of this issue, so I think it can be closed.

**Comment by NilsSve** [comment]
Thanks, and I see what you mean, It will now be closed.
