### ISSUE TITLE
'Add' in Export doesn't override the function if it already exists

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#31]
In the Export window, when doing 'Add All' multiple times, it simply overwrites all functions already in the list with a new version, but when you simply click "Add" multiple times, it just adds the same function as many times as you want, while I'd expect it to overwrite the already existing function. It should be save to overwrite any present function with the same name, because all functions come from the same file so naming conflicts should not be an issue.

**Comment by NilsSve** [comment]
An info_box was added to inform the user if a function had already been selected.
Fixed.
