### ISSUE TITLE
Fields aren't restricted to database column length in Function Maintenance

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#33]
I can type beyond the maximum field length of the help column for any function in Function Maintenance. I get an error saying 'Text is too large for database field', but restricting the field to the database field length in the first place would be a better user experience in my opinion.

**Comment by NilsSve** [comment]
I'm afraid that it is a limitation in the DataFlex language (or perhaps controls used within) when using the cTextEdit or cRichEdit classes. As these texts can contain many control characters, it "can't" or don't even try to set the limit of enterable character, as other db-controls does.

I think we just have to live with this limitation. I'm closing this issue but it might get re-opened at a later stage.
