### ISSUE TITLE
Very strange bug with "RemoveEndComments"

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#35]
Take the following test code:

```
Function test1 Returns Integer
End_Function /**/

Function test2 Returns Integer
End_Function //Comment
```

```This will keep '//Comment', even though I would expect it to be removed, but that's not the strange bit. If I change '/**/' to '/*' and refactor again, '//Comment' will still be there, so same result, BUT, if I now type '*/' after '/*', so it becomes '/**/' again and refactor again, '//Comment' will be gone. A second refactor will make '//Comment' appear again.```

I put the entire explanation in a code block to avoid markdown messing with the asterisks.

**Comment by Caeylinity** [comment]
Addition:

It seems that it alternatingly removes or leaves '//Comment' when pressing 'Start Refactoring' multiple times in a row with only 'RemoveEndComments' selected. When it removes '//Comment' the refactor takes a lot longer as well.

**Comment by Caeylinity** [comment]
Another update:

It seems to just ignore the entire refactor half of the time, not specifically removing '//Comment', but rather it skips the entire refactoring process.

**Comment by NilsSve** [comment]
This is a very special case and I'm not sure how we are going to handle it.

The thing is that the DFRefactor tool is for refactoring old legacy DataFlex code. But the tested approach above contains the new comment type that is new for DF 23. That example would not compile in an earlier version of DataFlex then 2023.

I think we shall put this issue aside for now. Maybe we can get back to it later?

**Comment by NilsSve** [comment]
I will close this issue for now. If needed we can reopen it later.

**Comment by Caeylinity** [comment]
You're right that this is a new feature, but it also prompted me to test images just to be sure, because it seems some form of '/' + '*' is causing this issue and I put the following at the top of my testbench BEFORE:

```
/TestImage
SELECT * FROM [TABLE]
*/
```

This caused the refactor to not work 100% of the time.

**Comment by NilsSve** [comment]
You are right, this needs further investigation.
I'm reopening this issue.

**Comment by NilsSve** [comment]
Fixed  bug in_IsDF23CommentStart and_IsDF23CommentEnd
Also changed the Tokenizer function so that the test for legacy "pages" aka /MyPage and end page sign /* is made prior to test for DF23 Multi-line comments/stings.
