### ISSUE TITLE
'ChangeInToContains' only changes in to contains when outside of brackets

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#37]
`If "stst" in "teststring"` will be changed to `If ("teststring" contains "stst")`, but `If ("stst" in "teststring")` wil remain `If ("stst" in "teststring")`

**Comment by NilsSve** [comment]
This is a limitation of the "in" operator. The operator is not valid to be used within an expression. If it does, it will generate a compile error.

As the issue isn't a refactoring issue per se, I will close it.
