### ISSUE TITLE
'RemovePropertyPrivate/Public' removes the word but doesn't remove spaces

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#39]
The following code:

```
Property Private String psStringProp "teststring"
Property Public String psStringProp "teststring"
```

turns into:

```
Property         String psStringProp "teststring"
Property        String psStringProp "teststring"
```

The keywords are removed, but an ugly empty space is left behind; this should be reduced to 1 space in my opinion. Not sure if this is intentional or a bug, but in my opinion this is a bug.

**Comment by NilsSve** [comment]
Fixed!
