### ISSUE TITLE
Changing 'Position for tab-pages' setting gives an error

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#54]
The following error pops up after changing the 'Position for tab-pages' setting:
![image](https://github.com/NilsSve/DfRefactor/assets/116262781/a2fe36b4-55ae-4654-b385-57fb85f48a9f)

It doesn't seem to affect the functionality of the setting, because the toolbar still moves to the selected spot.

**Comment by NilsSve** [comment]
Fixed!
The error comes from the usage of OnIdle timers that in this case, fire just when the program is to be restarted.

As it was hard to fix that, I reworked the logic, and it is no longer necessary to restart the program after altering the tab-pages setting.
