### ISSUE TITLE
'Run Unit Tests' doesn't work until you've compiled it from the studio

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#55]
I'm not 100% sure if this is a bug, but I'm reporting it anyway.

I clicked 'Run Unit Tests' and it told me it couldn't compile and I should check the studio. I then compiled the program in the studio (no changes, nothing to compile, so it was done instantly) and it worked fine afterwards. Maybe it was just missing an .exe?

**Comment by NilsSve** [comment]
Fixed! It can still happen in rare cases and that is when the compiled program is "busy" in e.g. Windows Defender scanning it after a recompile. A second attempt usually solves it.
