### ISSUE TITLE
Refactor doesn't work on initial 'install'

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#58]
After struggling with getting the 'Refactor' to work in the TestBench, I've figured out how to get it to work properly. I unchecked all functions, selected 1 and ran the refactoring, which now works. Then selecting all (as was the default setting) and refactored again and it worked. 

It seems there is some strange issue with the default setting of functions that blocks the refactor from working properly initially.

**Comment by NilsSve** [comment]
Probably the best way to ensure this doesn't happen to new users is to make sure that the Functions.Selected column values are all set to "0" (unselected) before deployment.

**Comment by NilsSve** [comment]
This should now work as expected.
