### ISSUE TITLE
Unicode input is not unicode output

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#59]
I noticed that the base testbench code has the following line:

`Send Stop_Box ("BekrÃ¤ftat lÃ¶senord stÃ¤mmer ej med nytt lÃ¶senord!")`

This turns into:

`Send Stop_Box ("Bekr?ftat l?senord st?mmer ej med nytt l?senord!")`

after refactoring.

The only refactoring function I have selected is `ChangeReplaceCommandToFunction`, so I don't think that should affect any kind of unicode/oem/ansi conversions. Could this be because the refactored code/tokens passing through a DF database (which does not support unicode)?

**Comment by NilsSve** [comment]
Fixed! This turned out to be much more complicated than first anticipated. There are many places where code needs to be translated back and forth between UTF8/OEM, but hopefully, all of them are now correct.
