### ISSUE TITLE
[Not TestBench]Can't start DFRefactor

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#60]
I accidentally compiled & started DFRefactor (from the studio) and I got the following error (rough translation from Dutch):
`The application can not be started because the side-by-side configuration is invalid. Check the application logs or use the command-line program sxstrace.exe for more information`.

I can't say I've ever seen this error before. I've tried booting DFRefactor from the TestBench as well, but that does nothing either.

I'm not sure how useful this bug report is, but it is something I came across by accident and it doesn't seem like expected behaviour.

**Comment by NilsSve** [comment]
Faulty .manifest files cause this.

To solve this we should get rid of the AppSrcManifestFiles.zip and also all COM CodeJock components from the Program folder (*.ocx).

**Comment by NilsSve** [comment]
The AppSrcManifstFles.zip has been removed and all programs has been set to automatically build the manifest file and embedd it. That should together take care of the problem.
