### ISSUE TITLE
Only select the line by key espace.

### ISSUE THREAD

**Issue by 2WA** [NilsSve/DfRefactor#62]
![DFRefactor-SelectFolders-FolderList](https://github.com/NilsSve/DfRefactor/assets/1987699/672f4f43-b979-462e-9028-93fd96987850)

Only one can select the line using the key space.

**Comment by NilsSve** [comment]
Thanks for the report.  Fixed!
A Function, CanEditColumn, which had been added to the grid, was causing this problem. That function has been commented out, and it is now possible to select a folder name by clicking the "Select" column.

**Comment by NilsSve** [comment]
Fixed.
