### ISSUE TITLE
Some files should be added to .gitignore

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#65]
I have opened the project in DataFlex 2023 studio and run a test with the Unused Source Files function. I also had a look at the settings dialog for the project.

This changes and adds some files in the AppSrc and Data folder. Git reports this and it should not be part of the source repository.

AppSrc/config/classlist.xml has changed. This file should not be part of the .git repostitory as it changes depending on the DataFlex studio used. It also changes depending on the local date settings.
An example would be this patch:
``` diff
diff --git a/AppSrc/config/classlist.xml b/AppSrc/config/classlist.xml
index c1e9f26..31d6e0b 100644
--- a/AppSrc/config/classlist.xml
+++ b/AppSrc/config/classlist.xml
@@ -1,31 +1,30 @@
 <?xml version="1.0"?>
 <classList xmlns="http://www.dataaccess.com/VisualDataFlex/2006/classlist/">
-       <VDFLibraryTimeStamp>2024-01-12T14:00:36</VDFLibraryTimeStamp>
-       <DFLibraryVersion>1</DFLibraryVersion>
+       <VDFLibraryTimeStamp>2023-07-24T17:47:23</VDFLibraryTimeStamp>
        <libraries>
                <library>
-                       <libraryPath>Libraries\vwin32fh\StudioLibrary\vWin32fh-Library-DF24.0.sws</libraryPath>
-                       <libraryTimeStamp>2023-04-30T09:36:03</libraryTimeStamp>
+                       <libraryPath>Libraries\vwin32fh\StudioLibrary\vWin32fh-Library-DF23.0.sws</libraryPath>
+                       <libraryTimeStamp>2024-03-26T15:24:26</libraryTimeStamp>
                        <libraryID>Lib1</libraryID>
                </library>
                <library>
-                       <libraryPath>Libraries\SciControlLib\SciControlLib24.0.sws</libraryPath>
-                       <libraryTimeStamp>2023-04-28T16:23:31</libraryTimeStamp>
+                       <libraryPath>Libraries\SciControlLib\SciControlLib23.0.sws</libraryPath>
+                       <libraryTimeStamp>2024-03-26T15:24:26</libraryTimeStamp>
                        <libraryID>Lib2</libraryID>
                </library>
```

The Data/ScintillaEdit.ini has been edited and a copy is made. This is also reflected in the git workspace like this:
```
$ git status Data
On branch users/age/feature/unusedsourcefilesfix
Your branch is up to date with 'origin/users/age/feature/unusedsourcefilesfix'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Data/ScintillaEdit.ini

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Data/DUFUpdateLog.txt
        Data/ScintillaEdit - Copy.ini

no changes added to commit (use "git add" and/or "git commit -a")
```

The Data/DUFUpdateLog.txt was added when running the dfrefactor application for the first time. This file should also be ignored by git.

However I am not sure if the settings should have been changed? There are a lot of changes in the ini file. The `Alpha test info DFrefactor project.txt` file states something like this:

> - Leave all project settings as they are (most importantly the 32-bit and manifest settings)
> - Do not use the DFRefactor program at this stage.

What does this mean? Can I use the settings dialog or is it causing issues? Does the `Data/ScintillaEdit.ini` file has anything to do with the above disclamer?

**Comment by SoftAllan** [comment]
I'll reset the project and download the DataFlex Studio 2024 to see if it is still the same problem.

**Comment by SoftAllan** [comment]
Excellent. I'll checkout the new commit and close this if they are present.

**Comment by SoftAllan** [comment]
Files has been added. I have removed the classlist in my upcomming PR.

**Comment by NilsSve** [comment]
OK, I'm now closing this issue as it seems to have been fixed.
