### ISSUE TITLE
Read me file refers to older dataflex version

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#67]
In the README.md file it is stated that 

> You need a DataFlex Studio 19.0 or later.

The help file under Wha's new for DFRefactor 2024.0 states this:

> The only DataFlex Studio version supported are the latest two. At current that means DataFlex 2023 and 2024. That doesn't mean that the program can't be used for projects/workspaces on earlier DataFlex versions. All this means is that one of the last two DataFlex Studio's needs to be installed to compile and run these refactoring programs.

The README.md file should be changed to reflect the new requirements.

**Comment by NilsSve** [comment]
Good point. Fixed!

**Comment by SoftAllan** [comment]
Wow that was fast!
