### ISSUE TITLE
RemoveMultipleBlankLines are listed in twice

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#69]
In the help file under Refactoring Functions menu the function `RemoveMultipleBlankLines` is listed twise. First time it is listed under the menu item "Remove- One File" (there is missing a space between "Remove" and "-" by the way), and the second place is under the menu item "Other - One File".

Having a look at the source files I can only find one reference to the function and here are a comment `// *** Type: eOther_Function ***` that it belongs to the Other menu item. The Remove menu item do have a much better description with example code though.

I suggest moving the description and example code from the Remove - One File menu item to the Other - One file menu item.
I suggest adding the missing space to the "Remove- One File" menu item.

**Comment by NilsSve** [comment]
Thanks for the report. Help text changed according to the suggestion.
Both local and "cloud" help updated.
