### ISSUE TITLE
The index files should be reindex before use

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#70]
I have installed DataFlex Studio 2024 with Danish collating. This is inconsistent with the index files in the DataDistrib.zip file. They are index with another collating. 
I suggest that the Readme.me file instructs that the database for the workspace has to be reindex with Database Builder. As it is dataflex developers that is using the application I think it is enough to mention this in the readme without full guidance on how to do.

**Comment by NilsSve** [comment]
Good suggestion, thanks. Done! By default, the collating sequence is English (standard DataFlex), and that info was also added to the readme file.
