### ISSUE TITLE
Clicking Run Unit Test from Test Bench application gives an error

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#73]
I get this error if I try to run the Unit Test application from within the Test Bench application

```
---------------------------
Information
---------------------------
The compilation of the DFUnit_TestRunner.src program failed and can't be started. Please check it with the Studio.
---------------------------
OK   
---------------------------

```

I am able to compile and run the unit test from the studio though.

**Comment by NilsSve** [comment]
Do *not* try to change this. The logic is fine and correct! But for some reason DataFlex may be unable to correctly compile the program and then you get this error message.
If this happens, just try again and it probably goes through.

**Comment by SoftAllan** [comment]
I tried with the following code
```
                #IFDEF IS$WIN64                
                    Move (Replace(".src", sSourceFile, "64.exe")) to sProgramFile
                #ELSE
                    Move (Replace(".src", sSourceFile, ".exe")) to sProgramFile
                #ENDIF
```
And tested with both 64 and 32 bit compilation of the TestBench.src. It works with 64 bit but it seems that the command for compiling the Unit test project is always compiling to 64 bit even if the TestBench.src is running in 32 bit.

**Comment by SoftAllan** [comment]
> Do _not_ try to change this. The logic is fine and correct! But for some reason DataFlex may be unable to correctly compile the program and then you get this error message. If this happens, just try again and it probably goes through.

I am not sure why the logic is correct on this?

**Comment by NilsSve** [comment]
The logic always calls the compiler and it is up to the compiler to decide if a re-compilation is needed or not. That is the first "Runprogram Wait..." line.

As all programs has been set to compile as x64 bits programs no changes should be necessary.

**Comment by NilsSve** [comment]
Right, I now see what you mean. The line "Get vFilePathExists (sProgramPath + sProgramFile) to bExists" should be moved to after the "Runprogram Wait...".

Thanks! Committed and pushed.

**Comment by SoftAllan** [comment]
I still think there is an issue here. You are checking for a file that is compiled with another exe file name. Please check to see, if you can make this work.

**Comment by SoftAllan** [comment]
What I mean is that the file compiles as DFUnit_TestRunner64.exe. But your are trying to find the file with the name: DFUnit_TestRunner.exe.

**Comment by NilsSve** [comment]
Yes, you are correct. The logic was flaky. And not only that, the logic also was duplicated in the two Run program toolbar items. A common method has been created: 
        // Common method for oExternalProgramsToolbar and oDFRefactor_MenuItem OnExectute.
        Procedure CompileRunProgram String sProgram

**Comment by NilsSve** [comment]
Fixed!
