### ISSUE TITLE
cUnusedSourceFiles does not handle UTF-8 BOM correctly

### ISSUE THREAD

**Issue by SoftAllan** [NilsSve/DfRefactor#74]
The report list files that are in use. However if the file is used in the beginning of another file that has a beginning BOM mark it is not listed.

**Comment by SoftAllan** [comment]
Hi Nils.
I created a Pull Request for you to approve. Can you have a look at it?

**Comment by NilsSve** [comment]
I have granted the Pull request and added a comment there.

**Comment by NilsSve** [comment]
Fixed by Allan.
